/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 800141
 */
public class MadLiterature extends javax.swing.JFrame {
        String[] madLib;
        int buttonPushed = 0;
        
    /**
     * Creates new form MadLiterature
     */
    public MadLiterature() {
        madLib = new String[4];
         questionBox.setText("What is your first name?");
         String useName = inputBox.getText();
        
        initComponents();
        initMadLib();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        storyBox = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        questionBox = new javax.swing.JTextField();
        inputBox = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        storyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        storyBox.setBackground(new java.awt.Color(0, 0, 0));
        storyBox.setColumns(20);
        storyBox.setFont(new java.awt.Font("Kristen ITC", 0, 13)); // NOI18N
        storyBox.setForeground(new java.awt.Color(255, 255, 255));
        storyBox.setRows(5);
        jScrollPane1.setViewportView(storyBox);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("             MAD LITERATURE");
        jLabel1.setOpaque(true);

        questionBox.setBackground(new java.awt.Color(0, 0, 0));
        questionBox.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        questionBox.setForeground(new java.awt.Color(0, 255, 255));

        inputBox.setBackground(new java.awt.Color(0, 0, 0));
        inputBox.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        inputBox.setForeground(new java.awt.Color(0, 255, 51));

        goButton.setBackground(new java.awt.Color(0, 0, 0));
        goButton.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        goButton.setForeground(new java.awt.Color(255, 102, 0));
        goButton.setText("GO!");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 11)); // NOI18N
        jLabel2.setText("Instructions: Answer the questions by typing in the input box. Hit go to continue. When Question says None, hit Story button to generate your story");

        storyButton.setBackground(new java.awt.Color(0, 0, 0));
        storyButton.setFont(new java.awt.Font("Kristen ITC", 0, 11)); // NOI18N
        storyButton.setForeground(new java.awt.Color(255, 255, 0));
        storyButton.setText("STORY");
        storyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inputBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(goButton)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                            .addComponent(questionBox))
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(storyButton)
                        .addGap(369, 369, 369))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goButton))
                .addGap(41, 41, 41)
                .addComponent(storyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
         //This code will take in the responses the user puts in & questions will need to update every time this is pushed.
         buttonPushed++;
         if(buttonPushed == 1){
              questionBox.setText("Give me a verb");
             String verb = inputBox.getText();
         }
         if(buttonPushed == 2){
         questionBox.setText("Give me an adjective");
         String adjective = inputBox.getText();
         }
         if(buttonPushed == 3){
         questionBox.setText("Give me a name");
         String name = inputBox.getText();
         }
         if(buttonPushed == 4){
         questionBox.setText("Give me a number");
         String number = inputBox.getText();
         }
         if(buttonPushed == 5){
         questionBox.setText("Give me an date");
         String date = inputBox.getText();
         }
         if(buttonPushed == 6){
         questionBox.setText("Give me an color");
         String color = inputBox.getText();
         }
         if(buttonPushed == 7){
         questionBox.setText("Give me an food");
         String food = inputBox.getText();
         }
     
         
         
         
    }//GEN-LAST:event_goButtonActionPerformed

    private void initMadLib(){
        //This is where the madlibs are
        
        madLib[0] = "\n On a "+adjective+", summer day, a white "+animal+ verb+" by you and said, “Hello." + name +
        "\n Hello white "+animal+" as you " +verb+ "The little white" +animal+ "continued on it's way as you continued on yours" +
        "\n Along the way, you hear someone call out Hello " +name+ "You turn to see the Mad Hatter.\n" + 
        "\n he hands you a china tea cup, though nothing appears to be in it. He then pores a" +color+ "liquid in cup"+
        "\n You give him a strange look before continuing on your way. While walking you see a floating" +food+ " and then a cresent smile. " +
        "\n Your eyes widen as you say" +interjection+ "The cheshire cat laughs at you as he disappears again" +
        "\n Continuing to walk, you think to yourself, 'This has been one" +adjective+ " day.";
        
        madLib[1] = "\n It was a " +adjective+ "night. You stare out the window, nothing seemingly interesting until" +name+ "appears in front of you"+
        "\n Your heart stops as " +interjection+ "escapes your lips." +name+ "begins to " +verb+ "around you. Suddenly everything around you disappears as" +
        "\n you reappear in" +place+ ". Your mind has now completely taken over. Now random" +food+ "begins" +adverb+ "for" +number+ "hours."+
        "\n You begin questioning the madness going on around you." +object+ "begin appearing as you travel through time. Upon arrival you see it is" +date+ "."+
        "\n You" + verb + "yourself and your eyes open to see everything around you is back to normal";
        
        madLib[2] = "\n A new and " +adjective+ "fairy princess is coming out soon! It will be about" +name+ "and the " +number+ " unicorns. Princess" +name+
        "\n is more" +adjective+ "than the current queen." +name+ "is forced to" +verb+ "from the kingdom and hide in the nearby" +place+ "." +
        "\n There she discovers the unicorns. She lives a normal life until" +number+ "days pass. The gueen discovers her location. She sends" +animal+
        "\n after her. The unicorns defend her from the queen's servent until finally Prince" +food+ "comes to her rescue. Together they live" + adjective+
        "\n ever after!";
       
        madLib[3] = "\n Let's build a snowman! First we need to have a really"+adjective+ "snowstorm, of course on "+date+ ". Watching all that" +object+
        "\n fall makes me" +verb+ "for a bowl of" +food+ "!" +interjection + "it's still" +adverb+ "abd there's alot of it! Let's go! Next is" +verb+
        "\n to go out in the cold. Once that is done, we need to get busy. We make a" +object+ "and" +verb+ "it in the" + place+ ". It gets so" +verb+
        "\n we can't roll it anymore. Then we do" +number+ "more and stack them on top of each other. We" +verb+ "for" +object+ "in the driveway for the"+
        "\n mouth, eyes, and ears. Mom gives us a scarf, hat, and " +food+ "to complete Mr." +name+ "!" +interjection+ "he's done!";
        
    }
    
    
    private void storyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storyButtonActionPerformed
        //This button is responsible to say "Print story"
        storyBox.setText(madLib[0]);
    }//GEN-LAST:event_storyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MadLiterature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MadLiterature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MadLiterature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MadLiterature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MadLiterature().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goButton;
    private javax.swing.JTextField inputBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField questionBox;
    private javax.swing.JTextArea storyBox;
    private javax.swing.JButton storyButton;
    // End of variables declaration//GEN-END:variables
}
